name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - uses: chrisjsimpson/deploy-wireguard-algo-vpn-action@v1
      with:
        ssh-private-key: ${{ secrets.SSHKEY }}
        public-ip: ${{ secrets.HOST }}
